services:
  - type: web
    name: scms-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__Provider
        value: Sqlite
      - key: Database__EnsureCreated
        value: "true"
      - key: Database__EnsurePermissionsSeeded
        value: "true"
      - key: Database__SeedDemoUsers
        value: "true"
      - key: Database__AutoSeedDemoData
        value: "true"
      - key: Database__AllowDemoSeeding
        value: "true"
      - key: Features__EnableScalarDocs
        value: "true"
      - key: Clinic__TimeZone
        value: Asia/Yangon
      - key: Jwt__SigningKey
        generateValue: true
      - key: Jwt__Issuer
        value: SCMS.Api
      - key: Jwt__Audience
        value: SCMS.Web
      - key: Gemini__Model
        value: gemini-3.5-flash-lite
      - key: Gemini__ApiKeys__0
        sync: false
      - key: Cloudinary__CloudName
        sync: false
      - key: Cloudinary__ApiKey
        sync: false
      - key: Cloudinary__ApiSecret
        sync: false
